#ifndef MULTIPLEX_CONSOLE_SCENE_H
#define MULTIPLEX_CONSOLE_SCENE_H

#include <stddef.h>
#include <stdint.h>

enum {
  MULTIPLEX_SCENE_MAGIC = 0x4e53504d,
  MULTIPLEX_SCENE_VERSION = 1,
  MULTIPLEX_SCENE_HEADER_SIZE = 64,
  MULTIPLEX_SCENE_COMMAND_SIZE = 72,
  MULTIPLEX_SCENE_MAX_COMMANDS = 1024,
  MULTIPLEX_SCENE_MAX_TEXT_BYTES = 8192,
  MULTIPLEX_SCENE_MAX_BYTES = 256 * 1024,
};

enum {
  MULTIPLEX_SCENE_COMMAND_KIND = 0,
  MULTIPLEX_SCENE_COMMAND_FLAGS = 2,
  MULTIPLEX_SCENE_COMMAND_X = 4,
  MULTIPLEX_SCENE_COMMAND_Y = 8,
  MULTIPLEX_SCENE_COMMAND_WIDTH = 12,
  MULTIPLEX_SCENE_COMMAND_HEIGHT = 16,
  MULTIPLEX_SCENE_COMMAND_X2 = 20,
  MULTIPLEX_SCENE_COMMAND_Y2 = 24,
  MULTIPLEX_SCENE_COMMAND_RADIUS = 28,
  MULTIPLEX_SCENE_COMMAND_STROKE_WIDTH = 32,
  MULTIPLEX_SCENE_COMMAND_COLOR = 36,
  MULTIPLEX_SCENE_COMMAND_CLIP_X = 40,
  MULTIPLEX_SCENE_COMMAND_CLIP_Y = 44,
  MULTIPLEX_SCENE_COMMAND_CLIP_WIDTH = 48,
  MULTIPLEX_SCENE_COMMAND_CLIP_HEIGHT = 52,
  MULTIPLEX_SCENE_COMMAND_TEXT_OFFSET = 56,
  MULTIPLEX_SCENE_COMMAND_TEXT_LENGTH = 60,
  MULTIPLEX_SCENE_COMMAND_GLYPH_ID = 64,
  MULTIPLEX_SCENE_COMMAND_FONT_SIZE = 68,
  MULTIPLEX_SCENE_REQUEST_KIND = 12,
  MULTIPLEX_SCENE_REQUEST_RATING_KEY = 60,
};

enum {
  MULTIPLEX_SCENE_REQUEST_NONE = 0,
  MULTIPLEX_SCENE_REQUEST_DETAILS = 1,
  MULTIPLEX_SCENE_REQUEST_PLAYBACK = 2,
};

enum {
  MULTIPLEX_SCENE_FLAG_CLIPPED = 1u << 0,
};

uint16_t multiplex_scene_read_u16(const uint8_t *bytes);
uint32_t multiplex_scene_read_u32(const uint8_t *bytes);
float multiplex_scene_read_f32(const uint8_t *bytes);
void multiplex_scene_write_u16(uint8_t *bytes, uint16_t value);
void multiplex_scene_write_u32(uint8_t *bytes, uint32_t value);
void multiplex_scene_write_f32(uint8_t *bytes, float value);
uint32_t multiplex_scene_crc32(const uint8_t *bytes, size_t size);

#endif
