"use client";

export {
  makeWatchTogetherApi,
  WatchTogetherApi,
  WatchTogetherApiError,
  type WatchTogetherApiShape,
} from "./watch-together-api";

export { PlexApiClient, makePlexHttpApiClient } from "./plex-api-client";
export {
  asAddToPlaylistResult,
  asContinueWatching,
  asCreatePlaylistResult,
  asHomeHubs,
  asHubContentPage,
  asItemDetails,
  asItemMetadata,
  asItemPlaylists,
  asLibraryCategories,
  asLibraryCollectionsPage,
  asLibraryContentPage,
  asLibraryFilterValues,
  asLibraryHubs,
  asLibraryMeta,
  asLibraryPivots,
  asLibraryPlaylistsPage,
  asLiveTvProgramming,
  asPlayQueue,
  asSearchResults,
  asServerLibraries,
  asUserInfo,
  asWatchTogetherRoom,
  asWatchTogetherRooms,
  stableRecordKey,
  type AddToPlaylistResult,
  type ContinueWatchingResult,
  type CreatePlaylistResult,
  type HomeHubsResult,
  type HubContentPage,
  type ItemDetails,
  type ItemPlaylistsResult,
  type LibraryCategoriesResult,
  type LibraryCollectionsPage,
  type LibraryContentPage,
  type LibraryFilterValuesResult,
  type LibraryHubsResult,
  type LibraryMetaResult,
  type LibraryPivotsResult,
  type LibraryPlaylistsPage,
  type LiveTvProgrammingResult,
  type SearchResults,
  type ServerLibrariesEntry,
  type ServerLibrariesResult,
  type UserInfoResult,
} from "./plex-boundary";
export {
  inviteesWriteKeys,
  itemMetadataWriteKeysFor,
  itemPlaylistsWriteKeysFor,
  pinnedSourceWriteKeys,
  playQueueWriteKeysFor,
  ReactivityKey,
  watchedStateWriteKeysFor,
  watchTogetherRoomWriteKeys,
  watchTogetherRoomWriteKeysFor,
} from "./reactivity-keys";
export {
  createPlayQueue,
  createWatchTogetherRoom,
  deleteWatchTogetherRoom,
  inviteWatchTogetherUsers,
  itemDetailsAtom,
  itemMetadataAtom,
  playQueueAtom,
  removeWatchTogetherRoomOptimistic,
  sendTimeline,
  userInfoAtom,
  watchTogetherInviteesAtom,
  watchTogetherRoomAtom,
  watchTogetherRoomsAtom,
  watchTogetherRoomsOptimisticAtom,
} from "./plex-atoms";
export {
  addItemToPlaylist,
  continueWatchingAtom,
  continueWatchingServerAtom,
  createPlaylistWithItem,
  fetchHubContentPage,
  fetchLibraryCollectionsPage,
  fetchLibraryContentPage,
  fetchLibraryPlaylistsPage,
  homeHubsAtom,
  hubContentPageAtom,
  itemPlaylistsAtom,
  libraryCategoriesAtom,
  libraryCollectionsPageAtom,
  libraryContentPageAtom,
  libraryFilterValuesAtom,
  libraryHubsAtom,
  libraryMetaAtom,
  libraryPivotsAtom,
  libraryPlaylistsPageAtom,
  liveTvAllProgrammingAtom,
  liveTvProgrammingAtom,
  searchAtom,
  serverLibrariesAtom,
  setItemWatchedState,
  togglePinnedSource,
  togglePinnedSourceOptimistic,
  updatePlayQueue,
  userInfoOptimisticAtom,
} from "./plex-browse-atoms";

export {
  makePlayerPort,
  PlayerPort,
  type PlayerActions,
  type PlayerPortShape,
  type PlayerSnapshot,
} from "./player-port";

export {
  createPlayerService,
  getBufferedPercent,
  getFormattedCurrentTime,
  getFormattedDuration,
  getIsReady,
  getPlayerStatus,
  getProgressPercent,
  initialPlayerState,
  makePlayerService,
  PlayerService,
  type PlayerPlaybackUpdate,
  type PlayerServiceShape,
  type PlayerState,
} from "./player-service";

export {
  playerCommands,
  playerStateAtom,
  usePlayerPlaybackState,
  usePlayerState,
  usePlayerStateSelector,
  type PlayerViewState,
} from "./player-atoms";

export {
  makeWatchTogetherSession,
  WatchTogetherSession,
  type EnterLobbyInput,
  type LeaveOptions,
  type LobbyContext,
  type MakeObserverConnection,
  type MakeSessionController,
  type MakeWatchTogetherSessionOptions,
  type ObserverConnectionLike,
  type RotationContext,
  type SessionControllerLike,
  type StartPlaybackInput,
  type SwapToInput,
  type WatchTogetherSessionShape,
} from "./session-service";

export {
  sessionCommands,
  sessionRuntime,
  sessionStateAtom,
  useSessionState,
} from "./session-atoms";

export { appEffectLayer } from "./runtime";

export { EffectRegistryProvider } from "./registry-provider";
