#ifndef MULTIPLEX_PLEX_HLS_CONTROL_TEST_MEDIA_SOURCE_H
#define MULTIPLEX_PLEX_HLS_CONTROL_TEST_MEDIA_SOURCE_H

#define MULTIPLEX_PLEX_VIDEO_RESOLUTION "480x270"
#define MULTIPLEX_PLEX_MAX_VIDEO_BITRATE "700"

#endif
